### ISSUE TITLE
queries with find_one({ key: value}) fail

### ISSUE THREAD

**Issue by dannygoldstein** [dmitryduev/broker#3]
`find_one` only works with no arguments. 

{
  "query_type": "general_search",
  "query": "db['legacysurveys_photoz_DR7'].find_one({'type': 'DEV'})",
  "kwargs": {
    "_id": "ta0ii87wfkg6jikm11kmkzns4ui9byel",
    "enqueue_only": true
  },
  "user": "danny"
}

returns

{
  "msg": "Traceback (most recent call last):\n  File \"/app/server.py\", line 865, in execute_query\n    query_result['query_result'] = await _select.to_list(length=None)\nAttributeError: 'NoneType' object has no attribute 'to_list'\n"
}

**Comment by dmitryduev** [comment]
Fixed, such queries will now return None.
Why? Because we're case-sensitive, so in this case should be "TYPE", not "type". You named it like that :)

**Comment by dannygoldstein** [comment]
🙇
